### ISSUE TITLE
Error In Example

### ISSUE THREAD

**Issue by okyere** [johndavedecano/FlaskDataTables#1]
When I run the example in the repo, I get:

Traceback (most recent call last):
  File "D:\Local_Git_Repositories\Web_Applications\flask_datatables\fdenv\lib\site-packages\flask\app.py", line 1836, in **call**
    return self.wsgi_app(environ, start_response)
  File "D:\Local_Git_Repositories\Web_Applications\flask_datatables\fdenv\lib\site-packages\flask\app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "D:\Local_Git_Repositories\Web_Applications\flask_datatables\fdenv\lib\site-packages\flask\app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Local_Git_Repositories\Web_Applications\flask_datatables\fdenv\lib\site-packages\flask_compat.py", line 33, in reraise
    raise value
  File "D:\Local_Git_Repositories\Web_Applications\flask_datatables\fdenv\lib\site-packages\flask\app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Local_Git_Repositories\Web_Applications\flask_datatables\fdenv\lib\site-packages\flask\app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Local_Git_Repositories\Web_Applications\flask_datatables\fdenv\lib\site-packages\flask\app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Local_Git_Repositories\Web_Applications\flask_datatables\fdenv\lib\site-packages\flask_compat.py", line 33, in reraise
    raise value
  File "D:\Local_Git_Repositories\Web_Applications\flask_datatables\fdenv\lib\site-packages\flask\app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Local_Git_Repositories\Web_Applications\flask_datatables\fdenv\lib\site-packages\flask\app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\Local_Git_Repositories\Web_Applications\flask_datatables\FlaskDataTables-master\app.py", line 9, in index
    return render_template('index.html', table=dataTables.render())
  File "D:\Local_Git_Repositories\Web_Applications\flask_datatables\FlaskDataTables-master\modules\datatables.py", line 74, in render
    html = self.__renderTable()
  File "D:\Local_Git_Repositories\Web_Applications\flask_datatables\FlaskDataTables-master\modules\datatables.py", line 58, in __renderTable
    table += self.__renderColumns()
  File "D:\Local_Git_Repositories\Web_Applications\flask_datatables\FlaskDataTables-master\modules\datatables.py", line 48, in __renderColumns
    html += '       <th align="center" valign="middle" class="head' + i.keys()[0] + '">' + i.values()[0] + '</th>\n'
TypeError: 'dict_keys' object does not support indexing

So it looks like something wrong with the datatables.py module. Are you still working on this?
Also, datatables 1.10.10 has a new api. Will you update this module accordingly to support it? Thanks.

**Comment by johndavedecano** [comment]
@okyere Yep its been that i have not updated this. I think its time to update this repository. Thanks for reporting.

**Comment by johndavedecano** [comment]
@okyere Problem with python 3

```
        for i in self.__columns:
            keys = list(i.keys())
            values = list(i.values())
            html += '       <th align="center" valign="middle" class="head' + keys[0] + '">' + values[0] + '</th>\n'

            self.__mData.append({"mData":str(values[0])})

        html += '  </tr>\n </thead>\n'
```
